-- liquibase formated sql
-- changeset sgorban:1

CREATE TABLE user_profile
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     TEXT,
    first_name TEXT,
    last_name  TEXT,
    phone     TEXT,
    role_enum  VARCHAR(5)

);

CREATE TABLE avatar
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data           bytea,
    user_profile_id BIGINT references user_profile (id)

);

ALTER TABLE user_profile
    ADD COLUMN avatar BIGINT references avatar (id);
CREATE TABLE image
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data      bytea,
    fileSize  BIGINT,
    mediaType TEXT
);

CREATE TABLE ads
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     TEXT,
    price           INTEGER,
    title           TEXT,
    user_profile_id BIGINT references user_profile (id),
    image_id        BIGINT references image (id)
);

CREATE TABLE comment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ads_id          BIGINT,
    user_profile_id BIGINT,
    created_at      TIMESTAMP,
    text            TEXT
);





